### ISSUE TITLE
prawcore.exceptions.ResponseException: received 401 HTTP response

### ISSUE THREAD

**Issue by AngelTiger90** [iam-abbas/Reddit-Stock-Trends#41]
**Hi, I follow the instruction to get the reddit API credentials 

However, I still have the following error.

Could you please help me why I get the error below?**

`Version 7.0.0 of praw is outdated. Version 7.1.4 was released 3 days ago.
Selecting relevant data from webscraper:   0% 0/2000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "ticker_counts.py", line 45, in <module>
    post.total_awards_received] for post in tqdm(new_bets, desc="Selecting relevant data from webscraper", total=WEBSCRAPER_LIMIT)]
  File "ticker_counts.py", line 40, in <listcomp>
    posts = [[post.id,
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/praw/models/listing/generator.py", line 61, in __next__
    self._next_batch()
  File "/usr/local/lib/python3.6/dist-packages/praw/models/listing/generator.py", line 71, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/usr/local/lib/python3.6/dist-packages/praw/reddit.py", line 490, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/usr/local/lib/python3.6/dist-packages/praw/reddit.py", line 574, in _objectify_request
    data=data, files=files, method=method, params=params, path=path
  File "/usr/local/lib/python3.6/dist-packages/praw/reddit.py", line 732, in request
    timeout=self.config.timeout,
  File "/usr/local/lib/python3.6/dist-packages/prawcore/sessions.py", line 339, in request
    url=url,
  File "/usr/local/lib/python3.6/dist-packages/prawcore/sessions.py", line 235, in _request_with_retries
    url,
  File "/usr/local/lib/python3.6/dist-packages/prawcore/sessions.py", line 195, in _make_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/prawcore/rate_limit.py", line 35, in call
    kwargs["headers"] = set_header_callback()
  File "/usr/local/lib/python3.6/dist-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/usr/local/lib/python3.6/dist-packages/prawcore/auth.py", line 325, in refresh
    self._request_token(grant_type="client_credentials")
  File "/usr/local/lib/python3.6/dist-packages/prawcore/auth.py", line 153, in _request_token
    response = self._authenticator._post(url, **data)
  File "/usr/local/lib/python3.6/dist-packages/prawcore/auth.py", line 36, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response`

**Comment by mpagels** [comment]
`eceived 401 HTTP response`
401 is an unauthorized error. Maybe your praw.ini is wrong?

**Comment by iam-abbas** [comment]
It means the your credentials are wrong

**Comment by AngelTiger90** [comment]
Hi, I create multiple apps and none is working.

Don't really understand why.

**Comment by AngelTiger90** [comment]
Hi,

It is my bad. I put the id and secret code in:  ''

I remove them all and it work fine with Google colab.

Thanks
