### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 503: Service Unavailable 

### ISSUE THREAD

**Issue by maxrugen** [iam-abbas/Reddit-Stock-Trends#43]
Running `yfinance_analysis.py` results in the following error, can someone help me please?

```python3
Traceback (most recent call last):
  File "/Users/maxrugen/Developer/Reddit-Stock-Trends/back/yfinance_analysis.py", line 71, in <module>
    analyzer.analyze()
  File "/Users/maxrugen/Developer/Reddit-Stock-Trends/back/yfinance_analysis.py", line 24, in analyze
    df_best[dataColumns] = df_best.Ticker.apply(self.get_ticker_info)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/series.py", line 4135, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2467, in pandas._libs.lib.map_infer
  File "/Users/maxrugen/Developer/Reddit-Stock-Trends/back/yfinance_analysis.py", line 46, in get_ticker_info
    info = yf.Ticker(ticker).info
  File "/usr/local/lib/python3.9/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/usr/local/lib/python3.9/site-packages/yfinance/base.py", line 446, in get_info
    self._get_fundamentals(proxy)
  File "/usr/local/lib/python3.9/site-packages/yfinance/base.py", line 285, in _get_fundamentals
    holders = _pd.read_html(url)
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/html.py", line 1085, in read_html
    return _parse(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/html.py", line 893, in _parse
    tables = p.parse_tables()
  File "/usr/local/lib/python3.9/site-packages/pandas/io/html.py", line 213, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/html.py", line 732, in _build_doc
    raise e
  File "/usr/local/lib/python3.9/site-packages/pandas/io/html.py", line 713, in _build_doc
    with urlopen(self.io) as f:
  File "/usr/local/lib/python3.9/site-packages/pandas/io/common.py", line 195, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by mpagels** [comment]
Do you have a firewall or app (like pihole) that blocks outgoing connections? Temporary disable them and try again.

**Comment by maxrugen** [comment]
Nope, not using anything like that. Tried using my phone's mobile data, no success either.

**Comment by iam-abbas** [comment]
Hello @maxrugen, this means you’re rate limited by Yahoo Finance API. Overusing the API could be one reason. We’re planning to change our API wrappers soon.

**Comment by maxrugen** [comment]
Thanks @iam-abbas, that's what I thought was happening.

**Comment by kztrp** [comment]
@maxrugen it is related to yfinance module. I couldn't use it earlier today, waited few hours and it started working. I think it is not related to overusing API because it crashed when i had ran it first time.

**Comment by maxrugen** [comment]
@kztrp Might be true, I've just been able to successfully run the script.
